#+title: r/roguelikedev summer tutorial 2021
#+date: <2021-06-25 Fri>
#+options: toc:nil

#+begin_comment

NOTE: this org file acted as my "diary". I exported it to html:

https://www.redblobgames.com/x/2126-roguelike-dev/

I don't expect that the org file itself will be useful to you, as it uses features that are only in my custom version of emacs. However, the html+js should work on its own.

#+end_comment

Each summer r/roguelikedev has a [[https://old.reddit.com/r/roguelikedev/wiki/python_tutorial_series][summer event]] in which we all make a simple roguelike, roughly following the libtcod roguelike tutorial. I've tried several times and actually finished in 2020, using [[https://ondras.github.io/rot.js/hp/][rot.js]] and Javascript. Last year, to keep the scope down, I told myself to implement only the topics from the tutorial, but make a list of things I might want to change.

#+include: "game.html" export html

This year, instead of going through the tutorial again from scratch, I'm going to revisit each chapter and try doing things differently. High level goals: tile graphics, thin walls (requiring a new map generator and a new field of view implementation), [[https://simblob.blogspot.com/2019/10/verb-noun-vs-noun-verb.html][noun-verb user interface]], more interesting monster behavior, redesigned stat and combat system, new control scheme, a small amount of animation.

Source code: [[href:game.html][game.html]] + [[href:roguelike-dev.ts][roguelike-dev.ts]] (build with esbuild) - and [[https://github.com/redblobgames/2126-roguelikedev][on github]].


#+begin_export html
<x:footer>
  <style>
    table.standard { border: 0; }
    table.standard th, table.standard td { font-family: var(--sans-serif); border-left-width: 0; border-right-width: 0; border-color: #ddd; }
    table.standard th { border-top-width: 0; background: unset; }

    figure img {
        display: block;
        margin: auto;
        border: 2px solid #999;
        box-shadow: 0 1px 2px 2px rgba(0,0,0,0.2);
    }
  </style>

  Created 18 Jun 2020 with the help of <a href="https://ondras.github.io/rot.js/hp/">rot.js</a>; &#160;
  <!-- hhmts start -->Last modified: 28 Jun 2021<!-- hhmts end -->
</x:footer>
#+end_export
